<?php

$mail_config = [

	/*
	|--------------------------------------------------------------------------
	| Mail Driver
	|--------------------------------------------------------------------------
	|
	| Laravel supports both SMTP and PHP's "mail" function as drivers for the
	| sending of e-mail. You may specify which one you're using throughout
	| your application here. By default, Laravel is setup for SMTP mail.
	|
	| Supported: "smtp", "mail", "sendmail", "mailgun", "mandrill",
	|            "ses", "sparkpost", "log"
	|
	*/

	'driver' => env('MAIL_DRIVER', 'log'),

	/*
	|--------------------------------------------------------------------------
	| SMTP Host Address
	|--------------------------------------------------------------------------
	|
	| Here you may provide the host address of the SMTP server used by your
	| applications. A default option is provided that is compatible with
	| the Mailgun mail service which will provide reliable deliveries.
	|
	*/

	'host' => env('MAIL_HOST', 'smtp.mailgun.org'),

	/*
	|--------------------------------------------------------------------------
	| SMTP Host Port
	|--------------------------------------------------------------------------
	|
	| This is the SMTP port used by your application to deliver e-mails to
	| users of the application. Like the host we have set this value to
	| stay compatible with the Mailgun e-mail application by default.
	|
	*/

	'port' => env('MAIL_PORT', 587),

	/*
	|--------------------------------------------------------------------------
	| Global "From" Address
	|--------------------------------------------------------------------------
	|
	| You may wish for all e-mails sent by your application to be sent from
	| the same address. Here, you may specify a name and address that is
	| used globally for all e-mails that are sent by your application.
	|
	*/

	'from' => [
		'address' => 'hello@example.com',
		'name' => 'Example',
	],

	/*
	|--------------------------------------------------------------------------
	| Global "Reply-To" Address
	|--------------------------------------------------------------------------
	*/
	'reply-to' => [
		'address' => 'laravel5boilerplate@mailinator.com',
		'name' => 'Laravel 5 boilerplate reply-to'
	],

	/*
	|--------------------------------------------------------------------------
	| Global "To" Address - FOR TESTING ONLY
	|--------------------------------------------------------------------------
	| https://laravel.com/docs/5.3/mail#mail-and-local-development
	|
	| A universal recipient of all e-mails sent by the framework. This way, all
	| the emails generated by your application will be sent to a specific
	| address, instead of the address actually specified when sending
	| the message. This should only be used for testing
	|
	*/
	// **this key will get removed in production**
	// (see code at the end of this file)
	'to' => [
		'address' => 'laravel5boilerplate@mailinator.com',
		'name' => 'Dev Testing'
	],

	/*
	|--------------------------------------------------------------------------
	| E-Mail Encryption Protocol
	|--------------------------------------------------------------------------
	|
	| Here you may specify the encryption protocol that should be used when
	| the application send e-mail messages. A sensible default using the
	| transport layer security protocol should provide great security.
	|
	*/

	'encryption' => env('MAIL_ENCRYPTION', 'tls'),

	/*
	|--------------------------------------------------------------------------
	| SMTP Server Username
	|--------------------------------------------------------------------------
	|
	| If your SMTP server requires a username for authentication, you should
	| set it here. This will get used to authenticate with your server on
	| connection. You may also set the "password" value below this one.
	|
	*/

	'username' => env('MAIL_USERNAME'),

	/*
	|--------------------------------------------------------------------------
	| SMTP Server Password
	|--------------------------------------------------------------------------
	|
	| Here you may set the password required by your SMTP server to send out
	| messages from your application. This will be given to the server on
	| connection so that the application will be able to send messages.
	|
	*/

	'password' => env('MAIL_PASSWORD'),

	/*
	|--------------------------------------------------------------------------
	| Sendmail System Path
	|--------------------------------------------------------------------------
	|
	| When using the "sendmail" driver to send e-mails, we will need to know
	| the path to where Sendmail lives on this server. A default path has
	| been provided here, which will work well on most of your systems.
	|
	*/

	'sendmail' => '/usr/sbin/sendmail -bs',

];

// Email re-routing (via a global "to" address is already set up in this config)
// turn this feature off in production
if(config('app.env') == 'production' || config('app.env') == 'prod')
{
	unset($mail_config['to']);
}

return $mail_config;